### PR TITLE
Feature/endpoint process images upload

### PR DESCRIPTION
**Pull request by ArceDaniel**

### CODE REVIEW

**Review by yocxy2 — APPROVED** [review]

**Review by yocxy2 — APPROVED** [review]
Okay recibido

**Review by yocxy2 — COMMENTED** [review]
bien

**Review by yocxy2 — APPROVED** [review]
bien solo recordar dias festivo para incluirlos ahora en tabla yde bd y no modificiar los enum

**Review by deiviiss — APPROVED** [review]
- Resolve conflict in gitignore and delete carets in dependencies.

**Review by lags2022 — APPROVED** [review]
Approved

**Pull request merged**
